"""Add auth system and created_by fields

Revision ID: 55adc69b9133
Revises: 001
Create Date: 2026-07-31 14:38:59.097019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55adc69b9133'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único del usuario'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Nombre de usuario único para login'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='Email del usuario (único)'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Contraseña hasheada con bcrypt'),
    sa.Column('full_name', sa.String(length=100), nullable=True, comment='Nombre completo del usuario'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Indica si el usuario está activo'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación del usuario'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha de última actualización'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    comment='Usuarios del sistema'
    )
    op.add_column('genexus_objects', sa.Column('created_by', sa.Integer(), nullable=True, comment='Usuario que creó el registro'))
    op.alter_column('genexus_objects', 'id',
               existing_type=sa.INTEGER(),
               comment='Identificador único del objeto (puede ser manual o autoincremental)',
               existing_comment='Identificador unico del objeto (autoincremental)',
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('genexus_objects', 'name',
               existing_type=sa.VARCHAR(length=128),
               comment='Nombre técnico del objeto GeneXus (ej: AhrPr001)',
               existing_comment='Nombre tecnico del objeto GeneXus (ej: AhrPr001)',
               existing_nullable=False)
    op.alter_column('genexus_objects', 'description',
               existing_type=sa.TEXT(),
               comment='Descripción funcional del objeto',
               existing_comment='Descripcion funcional del objeto',
               existing_nullable=True)
    op.alter_column('genexus_objects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Fecha de creación',
               existing_comment='Fecha de creacion',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('genexus_objects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Fecha de última actualización',
               existing_comment='Fecha de ultima actualizacion',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'genexus_objects', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('object_types', sa.Column('created_by', sa.Integer(), nullable=True, comment='Usuario que creó el registro'))
    op.alter_column('object_types', 'id',
               existing_type=sa.INTEGER(),
               comment='Identificador único del tipo de objeto (puede ser manual o autoincremental)',
               existing_comment='Identificador unico del tipo de objeto (autoincremental desde 0)',
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('object_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Fecha de creación',
               existing_comment='Fecha de creacion',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('object_types', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Fecha de última actualización',
               existing_comment='Fecha de ultima actualizacion',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'object_types', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_table_comment(
        'object_types',
        'Catálogo de tipos de objetos GeneXus',
        existing_comment='Tipos de objetos de GeneXus',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'object_types',
        'Tipos de objetos de GeneXus',
        existing_comment='Catálogo de tipos de objetos GeneXus',
        schema=None
    )
    op.drop_constraint(None, 'object_types', type_='foreignkey')
    op.alter_column('object_types', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Fecha de ultima actualizacion',
               existing_comment='Fecha de última actualización',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('object_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Fecha de creacion',
               existing_comment='Fecha de creación',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('object_types', 'id',
               existing_type=sa.INTEGER(),
               comment='Identificador unico del tipo de objeto (autoincremental desde 0)',
               existing_comment='Identificador único del tipo de objeto (puede ser manual o autoincremental)',
               existing_nullable=False,
               autoincrement=False)
    op.drop_column('object_types', 'created_by')
    op.drop_constraint(None, 'genexus_objects', type_='foreignkey')
    op.alter_column('genexus_objects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Fecha de ultima actualizacion',
               existing_comment='Fecha de última actualización',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('genexus_objects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Fecha de creacion',
               existing_comment='Fecha de creación',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('genexus_objects', 'description',
               existing_type=sa.TEXT(),
               comment='Descripcion funcional del objeto',
               existing_comment='Descripción funcional del objeto',
               existing_nullable=True)
    op.alter_column('genexus_objects', 'name',
               existing_type=sa.VARCHAR(length=128),
               comment='Nombre tecnico del objeto GeneXus (ej: AhrPr001)',
               existing_comment='Nombre técnico del objeto GeneXus (ej: AhrPr001)',
               existing_nullable=False)
    op.alter_column('genexus_objects', 'id',
               existing_type=sa.INTEGER(),
               comment='Identificador unico del objeto (autoincremental)',
               existing_comment='Identificador único del objeto (puede ser manual o autoincremental)',
               existing_nullable=False,
               autoincrement=False)
    op.drop_column('genexus_objects', 'created_by')
    op.drop_table('users')
    # ### end Alembic commands ###
