"""
Script para modificar las tablas y permitir IDs manuales.
Cambia GENERATED ALWAYS por GENERATED BY DEFAULT para permitir inserts con ID específico.
"""
import asyncio
import asyncpg
from dotenv import load_dotenv
import os

# Cargar variables de entorno
load_dotenv()

async def modificar_columnas():
    """Modifica las columnas de ID para permitir valores manuales."""
    database_url = os.getenv("DATABASE_URL", "")
    database_url = database_url.replace("postgresql+asyncpg://", "postgresql://")

    print("="*60)
    print("  PERMITIR IDS MANUALES")
    print("="*60)
    print()

    print("Conectando a la base de datos...")
    conn = await asyncpg.connect(database_url)

    try:
        print("\n[1/3] Obteniendo nombre de la secuencia...")
        # Obtener el nombre de la secuencia de identidad
        result = await conn.fetchrow("""
            SELECT pg_get_serial_sequence('genexus_objects', 'id') as seq_name;
        """)
        seq_name = result['seq_name'] if result else None
        print(f"  [INFO] Secuencia actual: {seq_name}")

        print("\n[2/3] Modificando genexus_objects...")
        # Remover la identidad ALWAYS
        await conn.execute("""
            ALTER TABLE genexus_objects
            ALTER COLUMN id DROP IDENTITY IF EXISTS;
        """)
        print("  [OK] Identidad removida")

        # Crear secuencia si no existe
        if not seq_name:
            print("  [INFO] Creando secuencia genexus_objects_id_seq...")
            await conn.execute("""
                CREATE SEQUENCE IF NOT EXISTS genexus_objects_id_seq
                START WITH 0
                INCREMENT BY 1
                MINVALUE 0
                NO MAXVALUE
                CACHE 1;
            """)
            seq_name = 'genexus_objects_id_seq'

        # Configurar el default con la secuencia
        await conn.execute(f"""
            ALTER TABLE genexus_objects
            ALTER COLUMN id SET DEFAULT nextval('{seq_name}');
        """)

        # Asociar la secuencia con la columna
        await conn.execute(f"""
            ALTER SEQUENCE {seq_name} OWNED BY genexus_objects.id;
        """)
        print("  [OK] Columna id de genexus_objects modificada")

        print("\n[3/3] Verificando object_types...")
        # object_types ya usa una secuencia manual, no necesita cambios
        print("  [OK] object_types ya está configurado correctamente")

        print("\n" + "="*60)
        print("  MODIFICACIÓN COMPLETADA")
        print("="*60)
        print("\n  Ahora puedes insertar registros con IDs manuales:")
        print("  - Sin ID: se autoincrementa")
        print("  - Con ID: se usa el ID especificado (incluyendo 0)")

    except Exception as e:
        print(f"\n[ERROR] Error: {e}")
        raise

    finally:
        await conn.close()
        print("\nConexión cerrada.")

if __name__ == "__main__":
    asyncio.run(modificar_columnas())
